branches:
  only:
    - "master"

if: commit_message =~ /\[(test travis|run travis)\]/ OR type = push

language: python

cache: pip

env:
  global:

matrix:
  include:
    - stage: "Lint and Code Style"
      python: 3.7
      env: TOXENV=lint

    - stage: "Tests and Coverage"
      python: 3.7
      env: TOXENV=py37

    - stage: "Docs"
      python: 3.7
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox -vv
