[tox]
minversion = 3.1.0
requires = virtualenv >= 20.0.0
source = atlalign
envlist =
    lint
    py37
    docs

[testenv]
download = true
extras =
    dev
    tf
commands =
    pytest {posargs:tests}

[testenv:lint]
basepython = python3.7
skip_install = true
deps =
    flake8
    isort
    pydocstyle
    black
commands =
    flake8 setup.py {[tox]source} tests
    isort --honor-noqa --profile=black --check setup.py {[tox]source} tests
    pydocstyle {[tox]source}
    black -q --check setup.py {[tox]source} tests

[testenv:format]
basepython = python3.7
skip_install = true
deps =
    isort
    black
commands =
    isort --honor-noqa --profile=black setup.py {[tox]source} tests
    black setup.py {[tox]source} tests

[testenv:docs]
basepython = python3.7
extras =
    dev
    tf
    docs
commands =
    sphinx-build -b doctest docs/ docs/_build/

[pytest]
addopts =
    -v
    -m "not todo and not slow and not internet"
    --disable-warnings
    --strict
    --cov=atlalign
    --cov-report=term-missing
testpaths = tests
markers =
    internet: requires connection to the internet
    slow: mark denoting a test that is too slow
    todo: mark denoting a test that is not written yet

[flake8]
count = True
max-line-length = 120
ignore = E402, W503, E203

[pydocstyle]
convention = numpy
