name: ci testsing


on:
  push:
    branches: master
  pull_request:
    if: "!contains(github.event.head_commit.message, 'skip ci')"


jobs:

  run_test:

    runs-on:
      ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7]  # currently ANTsPy wheels are only avail for py37

    steps:

      - name: checkout latest commit
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: linting and code style
        run: tox -vv lint

      - name: tests and coverage
        run: tox -vv py37

      - name: docs
        run: tox -vv docs
