name: ci testing


on:
  push:
    branches: master
  pull_request:


jobs:

  run_test:

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:
        os: [ubuntu-latest] # macos 11 is currently in preview, macos-latest == 1.10.15
        python-version: [
          3.9,
        ]
        include:
          - python-version: 3.9
            tox-env: py39

    steps:

      - name: checkout latest commit
        uses: actions/checkout@v2

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: linting and code style
        run: tox -vv -e lint

      - name: tests and coverage
        run: tox -vv -e ${{ matrix.tox-env }} -- --color=yes

      - name: docs
        run: tox -vv -e docs
