name: ci testing


on:
  push:
    branches: master
  pull_request:


jobs:

  run_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]  # currently ANTsPy wheels are only avail for py37

    steps:

      - name: checkout latest commit
        uses: actions/checkout@v2

      - name: echo commit message
        run: |
           echo ${{ github.event.head_commit.message }}

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: linting and code style
        run: tox -vv -e lint

      - name: tests and coverage
        run: tox -vv -e py37

      - name: docs
        run: tox -vv -e docs
